import { Property } from "./types";

const mockDatabase: Property[] = [
  {
    id: "1",
    title: "Modern Apartment",
    price: 300000,
    location: "New York, NY",
    specs: { beds: 2, baths: 2, area: 1000 },
    images: ["image1.jpg", "image2.jpg"],
    status: "available",
  },
  {
    id: "2",
    title: "Cozy House",
    price: 250000,
    location: "Los Angeles, CA",
    specs: { beds: 3, baths: 2, area: 1500 },
    images: ["image3.jpg", "image4.jpg"],
    status: "sold",
  },
  {
    id: "3",
    title: "Luxury Villa",
    price: 500000,
    location: "Miami, FL",
    specs: { beds: 5, baths: 4, area: 3500 },
    images: ["image5.jpg", "image6.jpg"],
    status: "available",
  },
  {
    id: "4",
    title: "Beachfront Property",
    price: 750000,
    location: "Honolulu, HI",
    specs: { beds: 4, baths: 3, area: 2500 },
    images: ["image7.jpg", "image8.jpg"],
    status: "available",
  },
  {
    id: "5",
    title: "Charming Cottage",
    price: 180000,
    location: "Portland, OR",
    specs: { beds: 2, baths: 1, area: 900 },
    images: ["image9.jpg", "image10.jpg"],
    status: "available",
  },
  {
    id: "6",
    title: "Spacious Loft",
    price: 320000,
    location: "Chicago, IL",
    specs: { beds: 3, baths: 2, area: 2200 },
    images: ["image11.jpg", "image12.jpg"],
    status: "available",
  },
  {
    id: "7",
    title: "Penthouse Suite",
    price: 950000,
    location: "San Francisco, CA",
    specs: { beds: 4, baths: 3, area: 4000 },
    images: ["image13.jpg", "image14.jpg"],
    status: "available",
  },
  {
    id: "8",
    title: "Suburban Retreat",
    price: 270000,
    location: "Dallas, TX",
    specs: { beds: 3, baths: 2, area: 1800 },
    images: ["image15.jpg", "image16.jpg"],
    status: "available",
  },
  {
    id: "9",
    title: "Country Estate",
    price: 650000,
    location: "Austin, TX",
    specs: { beds: 5, baths: 4, area: 5000 },
    images: ["image17.jpg", "image18.jpg"],
    status: "sold",
  },
  {
    id: "10",
    title: "Historic Mansion",
    price: 1000000,
    location: "Boston, MA",
    specs: { beds: 6, baths: 5, area: 6000 },
    images: ["image19.jpg", "image20.jpg"],
    status: "available",
  },
  {
    id: "11",
    title: "Rural Farmhouse",
    price: 200000,
    location: "Nashville, TN",
    specs: { beds: 4, baths: 3, area: 2800 },
    images: ["image21.jpg", "image22.jpg"],
    status: "available",
  },
  {
    id: "12",
    title: "Mountain Cabin",
    price: 350000,
    location: "Denver, CO",
    specs: { beds: 3, baths: 2, area: 2200 },
    images: ["image23.jpg", "image24.jpg"],
    status: "sold",
  },
  {
    id: "13",
    title: "Suburban Family Home",
    price: 280000,
    location: "Seattle, WA",
    specs: { beds: 3, baths: 2, area: 1900 },
    images: ["image25.jpg", "image26.jpg"],
    status: "available",
  },
  {
    id: "14",
    title: "Luxury Condo",
    price: 450000,
    location: "San Diego, CA",
    specs: { beds: 2, baths: 2, area: 1500 },
    images: ["image27.jpg", "image28.jpg"],
    status: "sold",
  },
  {
    id: "15",
    title: "Modern Townhouse",
    price: 380000,
    location: "Washington, DC",
    specs: { beds: 3, baths: 2, area: 1800 },
    images: ["image29.jpg", "image30.jpg"],
    status: "available",
  },
  {
    id: "16",
    title: "Luxury Lake House",
    price: 800000,
    location: "Lake Tahoe, CA",
    specs: { beds: 4, baths: 3, area: 3000 },
    images: ["image31.jpg", "image32.jpg"],
    status: "sold",
  },
  {
    id: "17",
    title: "Coastal Retreat",
    price: 600000,
    location: "Santa Barbara, CA",
    specs: { beds: 4, baths: 3, area: 2800 },
    images: ["image33.jpg", "image34.jpg"],
    status: "available",
  },
  {
    id: "18",
    title: "Urban Studio",
    price: 220000,
    location: "Atlanta, GA",
    specs: { beds: 1, baths: 1, area: 700 },
    images: ["image35.jpg", "image36.jpg"],
    status: "available",
  },
  {
    id: "19",
    title: "Luxury Penthouse",
    price: 1200000,
    location: "Chicago, IL",
    specs: { beds: 5, baths: 5, area: 5000 },
    images: ["image37.jpg", "image38.jpg"],
    status: "sold",
  },
  {
    id: "20",
    title: "Beachside Bungalow",
    price: 650000,
    location: "Malibu, CA",
    specs: { beds: 3, baths: 2, area: 2300 },
    images: ["image39.jpg", "image40.jpg"],
    status: "available",
  },
  {
    id: "21",
    title: "City Loft",
    price: 400000,
    location: "Boston, MA",
    specs: { beds: 2, baths: 1, area: 1200 },
    images: ["image41.jpg", "image42.jpg"],
    status: "sold",
  },
  {
    id: "22",
    title: "Countryside Cottage",
    price: 180000,
    location: "Tucson, AZ",
    specs: { beds: 2, baths: 1, area: 950 },
    images: ["image43.jpg", "image44.jpg"],
    status: "available",
  },
  {
    id: "23",
    title: "Modern Mansion",
    price: 900000,
    location: "Austin, TX",
    specs: { beds: 5, baths: 5, area: 4000 },
    images: ["image45.jpg", "image46.jpg"],
    status: "available",
  },
  {
    id: "24",
    title: "Oceanfront Estate",
    price: 1100000,
    location: "Miami, FL",
    specs: { beds: 6, baths: 5, area: 5500 },
    images: ["image47.jpg", "image48.jpg"],
    status: "sold",
  },
  {
    id: "25",
    title: "Eco-Friendly Home",
    price: 420000,
    location: "Portland, OR",
    specs: { beds: 3, baths: 2, area: 2100 },
    images: ["image49.jpg", "image50.jpg"],
    status: "available",
  },
  {
    id: "26",
    title: "Urban Loft",
    price: 375000,
    location: "Seattle, WA",
    specs: { beds: 2, baths: 1, area: 1100 },
    images: ["image51.jpg", "image52.jpg"],
    status: "available",
  },
  {
    id: "27",
    title: "Country Ranch",
    price: 800000,
    location: "Dallas, TX",
    specs: { beds: 5, baths: 4, area: 4200 },
    images: ["image53.jpg", "image54.jpg"],
    status: "sold",
  },
  {
    id: "28",
    title: "Suburban Retreat",
    price: 265000,
    location: "San Antonio, TX",
    specs: { beds: 3, baths: 2, area: 2000 },
    images: ["image55.jpg", "image56.jpg"],
    status: "available",
  },
  {
    id: "29",
    title: "Rustic Log Cabin",
    price: 350000,
    location: "Denver, CO",
    specs: { beds: 4, baths: 3, area: 2200 },
    images: ["image57.jpg", "image58.jpg"],
    status: "available",
  },
  {
    id: "30",
    title: "Contemporary House",
    price: 500000,
    location: "Austin, TX",
    specs: { beds: 4, baths: 3, area: 2800 },
    images: ["image59.jpg", "image60.jpg"],
    status: "available",
  },
  {
    id: "31",
    title: "Seaside Villa",
    price: 900000,
    location: "Key West, FL",
    specs: { beds: 4, baths: 4, area: 3500 },
    images: ["image61.jpg", "image62.jpg"],
    status: "sold",
  },
  {
    id: "32",
    title: "Mountain Retreat",
    price: 450000,
    location: "Denver, CO",
    specs: { beds: 3, baths: 2, area: 2100 },
    images: ["image63.jpg", "image64.jpg"],
    status: "available",
  },
  {
    id: "33",
    title: "Luxury Condominium",
    price: 600000,
    location: "San Diego, CA",
    specs: { beds: 3, baths: 3, area: 2500 },
    images: ["image65.jpg", "image66.jpg"],
    status: "sold",
  },
  {
    id: "34",
    title: "New York Penthouse",
    price: 1500000,
    location: "New York, NY",
    specs: { beds: 5, baths: 5, area: 6000 },
    images: ["image67.jpg", "image68.jpg"],
    status: "available",
  },
  {
    id: "35",
    title: "Lakeview Home",
    price: 350000,
    location: "Chicago, IL",
    specs: { beds: 4, baths: 3, area: 2400 },
    images: ["image69.jpg", "image70.jpg"],
    status: "available",
  },
  {
    id: "36",
    title: "Farmstead",
    price: 150000,
    location: "Sacramento, CA",
    specs: { beds: 2, baths: 1, area: 1200 },
    images: ["image71.jpg", "image72.jpg"],
    status: "available",
  },
  {
    id: "37",
    title: "Historic Mansion",
    price: 750000,
    location: "Charleston, SC",
    specs: { beds: 5, baths: 4, area: 4800 },
    images: ["image73.jpg", "image74.jpg"],
    status: "sold",
  },
  {
    id: "38",
    title: "City Loft",
    price: 380000,
    location: "Los Angeles, CA",
    specs: { beds: 2, baths: 2, area: 1300 },
    images: ["image75.jpg", "image76.jpg"],
    status: "available",
  },
  {
    id: "39",
    title: "Rural Retreat",
    price: 280000,
    location: "Montana",
    specs: { beds: 3, baths: 2, area: 2000 },
    images: ["image77.jpg", "image78.jpg"],
    status: "available",
  },
  {
    id: "40",
    title: "Luxury Loft",
    price: 500000,
    location: "Miami, FL",
    specs: { beds: 3, baths: 3, area: 2700 },
    images: ["image79.jpg", "image80.jpg"],
    status: "sold",
  },
];

export async function searchProperties(filters: {
  location?: string;
  price?: number;
}) {
  return mockDatabase.filter((property) => {
    const matchesLocation = filters.location
      ? property.location.toLowerCase().includes(filters.location)
      : true;

    const matchesPrice = filters.price ? property.price <= filters.price : true;

    return matchesLocation && matchesPrice;
  });
}

export async function getPropertyById(id: string) {
  return mockDatabase.find((property) => property.id === id);
}

export async function favoriteProperty(id: string) {
  return { id, status: "available" };
}
