import type { Metadata } from "next";
import "./globals.css";
import Footer from "@/components/core/footer";
import FilterPanel from "@/components/client/filter-panel";

export const metadata: Metadata = {
  title: "Property List",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="relative">
        <FilterPanel />
        {children}
        <Footer />
      </body>
    </html>
  );
}
